### ISSUE TITLE
yield appears not to be supported?

### ISSUE THREAD

**Issue by gkovacs** [dk00/livescript-next#5]
```
a = (name) ->*
  yield foo()
```

with livescript-next

```
Error: t.ls: not implemented: Yield (2:2)
  1 | a = (name) ->*
  2 |   yield foo()
    at /Users/geza/livescript-next/node_modules/livescript-next/lib/convert.js:136:43
    at t (/Users/geza/livescript-next/node_modules/livescript-next/lib/convert.js:138:4)
    at convertAll (/Users/geza/livescript-next/node_modules/livescript-next/lib/convert.js:192:42)
    at /Users/geza/livescript-next/node_modules/livescript-next/lib/convert.js:190:28
    at Array.reduce (native)
    at convertAll (/Users/geza/livescript-next/node_modules/livescript-next/lib/convert.js:187:53)
    at convertChildren (/Users/geza/livescript-next/node_modules/livescript-next/lib/convert.js:198:23)
    at /Users/geza/livescript-next/node_modules/livescript-next/lib/convert.js:134:66
    at t (/Users/geza/livescript-next/node_modules/livescript-next/lib/convert.js:138:4)
    at convertAll (/Users/geza/livescript-next/node_modules/livescript-next/lib/convert.js:192:42)
```

with standard livescript:

```
// Generated by LiveScript 1.5.0
(function(){
  var a;
  a = function*(name){
    return (yield foo());
  };
}).call(this);
```

**Comment by dk00** [comment]
`yield` is simply not implemented yet, as the error message says.

Generate functions (`->*`, `function*`) and `yield` expressions will be implemented and enabled in next release.
